CREATE TABLE ClassesLS5 (
ClassID VARCHAR(10) PRIMARY KEY,
ClassName VARCHAR(10) NOT NULL,
Year DATE  NOT NULL
);
CREATE TABLE studentsLS5 (
studentsID VARCHAR(10) PRIMARY KEY,
Fullname VARCHAR(30) NOT NULL,
Birthday DATE NOT NULL,
Sex VARCHAR (10),
ClassID VARCHAR(10),
CONSTRAINT stu_cla
FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
);