CREATE TABLE Users (
UserID VARCHAR(100) PRIMARY KEY NOT NULL,
Username VARCHAR(100) UNIQUE,
Password VARCHAR(20) NOT NULL,
Email VARCHAR(100) UNIQUE,
Status ENUM('ONLINE' ,'OFFLINE')
);
ALTER TABLE Users 
ADD CONSTRAINT Check_value CHECK (Status in ('ONLINE','OFFLINE'));
DROP TABLE Users;