CREATE TABLE Orders(
OrderID VARCHAR(20) PRIMARY KEY NOT NULL,
OrderDay DATETIME NOT NULL,
Status_Orders ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
Price DECIMAL(10,2) NOT NULL 
);
CREATE TABLE Product (
ProductID VARCHAR(20) PRIMARY KEY NOT NULL,
Color VARCHAR(50),
Brand VARCHAR(50),
Made_in VARCHAR(50)
);
CREATE TABLE Order_items (
OrderID VARCHAR(20) NOT NULL,
ProductID VARCHAR(20) NOT NULL,
PRIMARY KEY(OrderID,ProductID),
CONSTRAINT orderItem FOREIGN KEY (OrderID)
REFERENCES orders(OrderID),
CONSTRAINT productItem FOREIGN KEY (ProductID)
REFERENCES Product(ProductID)  
);