CREATE TABLE StudentsLS35 (
StudentID VARCHAR(20) PRIMARY KEY NOT NULL,
Fullname VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL
);
CREATE TABLE Course (
CorseID VARCHAR(20) PRIMARY KEY NOT NULL,
CourseName VARCHAR(100) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
Describe_Course VARCHAR(200) 
);
CREATE TABLE enrollments(
StudentID VARCHAR(20) NOT NULL,
CorseID VARCHAR(20) NOT NULL,
PRIMARY KEY (StudentID, CorseID),
CONSTRAINT Student_items FOREIGN KEY (StudentID)
REFERENCES StudentsLS35(StudentID),
CONSTRAINT Course_items FOREIGN KEY (CorseID)
REFERENCES Course(CorseID)
);
CREATE TABLE teacher (
TeacherID VARCHAR(20) PRIMARY KEY NOT NULL,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
CorseID VARCHAR(20) NOT NULL,
CONSTRAINT Tea_cou 
FOREIGN KEY (CorseID) REFERENCES Course(CorseID) 
);
ALTER TABLE Course 
ADD CONSTRAINT check_price CHECK (Price >0);
DROP TABLE enrollments;